/**
 * Reset the bot to a known demo state.
 *
 * Runs in Node, not in the Worker — `npm run seed` — and talks to D1 through
 * `wrangler d1 execute`. It deletes and rewrites rows, which the application
 * itself never does: the event log is append-only by design, and an operator
 * resetting a demo is the one case that sits outside that rule.
 *
 * What it builds:
 *   last week   an ordered week with two verdicts, so `/snack rate` has
 *               something to rate and scores show up on re-adds
 *   this week   six items with uneven votes and prices, chosen so the $50
 *               budget line falls in the middle of the list
 *   catalog     the same products, so keyword search returns hits
 *
 * Seeded items have no `message_id`, because no Discord card was ever posted
 * for them. They appear in `/snack list` and the digest but have no vote
 * button — add one live to demo the card itself.
 */
import 'dotenv/config';
import { execFileSync } from 'node:child_process';
import { writeFileSync, unlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { isoWeek, nextIsoWeek, prevIsoWeek } from '../src/util/week.ts';
import { ulid } from '../src/util/id.ts';

const THIS = isoWeek();
const LAST = prevIsoWeek();
const NEXT = nextIsoWeek();
/** Two weeks back, so a stale `rate` target can't shadow the seeded one. */
const BEFORE = prevIsoWeek(new Date(Date.now() - 7 * 86_400_000));
const BUDGET_CENTS = 5000;

/** Fake but plausible Discord snowflakes, so votes come from distinct people. */
const PEOPLE = ['200000000000000001', '200000000000000002', '200000000000000003', '200000000000000004', '200000000000000005'];
const ME = process.env.DISCORD_SEED_USER_ID ?? PEOPLE[0]!;

interface Seed {
  asin: string;
  title: string;
  price_cents: number;
  pack_size: number | null;
  category: string;
  department: string;
  /** How many people back it, including the requester. */
  votes: number;
}

// Sorted by votes at digest time; at a $50 cap the line lands after Dot's,
// leaving the last two to roll over with their votes.
const CURRENT: Seed[] = [
  { asin: 'B0DL2LVM8Z', title: "Dot's Pretzels Twists, 3-Flavor Snacks Variety Pack, 18 count", price_cents: 997, pack_size: 18, category: 'grocery', department: 'Grocery & Gourmet Food', votes: 5 },
  { asin: 'B0947SQPQ2', title: 'Oreo Chocolate Sandwich Cookies, 3 Pack', price_cents: 799, pack_size: 3, category: 'grocery', department: 'Grocery & Gourmet Food', votes: 4 },
  { asin: 'B08NZNPZS8', title: 'ORBIT Peppermint Sugar Free Chewing Gum, 200-Piece Bag', price_cents: 2285, pack_size: 200, category: 'grocery', department: 'Grocery & Gourmet Food', votes: 3 },
  { asin: 'B06Y6485FQ', title: 'Black Forest USDA Organic Gummy Bears, 65 Pouches', price_cents: 1749, pack_size: 65, category: 'toys-and-games', department: 'Grocery & Gourmet Food', votes: 2 },
  { asin: 'B09PYB4MQS', title: 'Barebells Protein Bars Variety Pack, 12 Count', price_cents: 3249, pack_size: 12, category: 'grocery', department: 'Health & Household', votes: 2 },
  { asin: 'B007JTC9JA', title: 'Haribo Gold Bears, 100 Mini Bags', price_cents: 3892, pack_size: 100, category: 'grocery', department: 'Grocery & Gourmet Food', votes: 1 },
];

// Last week shipped these. The energy drinks were a hit, the sparkling water
// was not — so both carry a score into this week's adds.
const DELIVERED: (Seed & { verdict: 'liked' | 'disliked' })[] = [
  { asin: 'B0DQ6T9ZHV', title: 'Alani Nu Variety Pack Energy Drinks, 12 Fl Oz, 12 Pack', price_cents: 2999, pack_size: 12, category: 'grocery', department: 'Grocery & Gourmet Food', votes: 4, verdict: 'liked' },
  { asin: 'B07Q5RVKS8', title: 'Poland Spring Sparkling Water, Lemon, 24 Pack', price_cents: 1599, pack_size: 24, category: 'grocery', department: 'Grocery & Gourmet Food', votes: 2, verdict: 'disliked' },
];

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;
const n = (v: number | null) => (v === null ? 'NULL' : String(v));

const sql: string[] = ['-- generated by scripts/seed.ts; safe to re-run'];
let clock = 0;
const sk = () => `ts#${new Date(Date.UTC(2026, 0, 1, 9, 0, clock++)).toISOString()}#${ulid()}`;

function event(week: string, type: string, itemId: string, actor: string, s?: Seed) {
  sql.push(
    `INSERT INTO events (week, sk, type, item_id, actor_id, asin, title, price_cents, image_url, pack_size, qty, message_id, allergens) VALUES (` +
      [
        q(week), q(sk()), q(type), q(itemId), q(actor),
        s ? q(s.asin) : 'NULL',
        s ? q(s.title) : 'NULL',
        s ? n(s.price_cents) : 'NULL',
        "''",
        s ? n(s.pack_size) : 'NULL',
        s ? '1' : 'NULL',
        'NULL', 'NULL',
      ].join(', ') +
      `);`,
  );
}

// Wipe the four weeks a demo can reach — including next week, which collects
// rolled-over items and otherwise arrives pre-populated with junk from the
// last run. Weeks older than these are left alone.
sql.push(`DELETE FROM events WHERE week IN (${[BEFORE, LAST, THIS, NEXT].map(q).join(', ')});`);
sql.push('DELETE FROM scores;');
sql.push('DELETE FROM products;');

// Pin the budget too, or the cut line falls wherever the last demo left it.
sql.push(
  `INSERT INTO settings (key, value, updated_at, updated_by) VALUES ('budget_cents', ${q(String(BUDGET_CENTS))}, ${q(new Date().toISOString())}, 'seed')` +
    ` ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at, updated_by = excluded.updated_by;`,
);

for (const s of [...CURRENT, ...DELIVERED]) {
  sql.push(
    `INSERT INTO products (asin, title, price_cents, pack_size, image_url, category, department, first_seen, last_fetched) VALUES (` +
      [q(s.asin), q(s.title), n(s.price_cents), n(s.pack_size), "''", q(s.category), q(s.department), q('2026-09-01T00:00:00.000Z'), q(new Date().toISOString())].join(', ') +
      `);`,
  );
}

// Last week: added, ordered, then a verdict each.
for (const s of DELIVERED) {
  const id = ulid();
  event(LAST, 'added', id, ME, s);
  for (let v = 1; v < s.votes; v++) event(LAST, 'voted', id, PEOPLE[v % PEOPLE.length]!, undefined);
  event(LAST, 'ordered', id, ME, s);
  event(LAST, s.verdict, id, PEOPLE[1]!, undefined);
  sql.push(
    `INSERT INTO scores (asin, likes, dislikes, last_rated) VALUES (${q(s.asin)}, ${s.verdict === 'liked' ? 3 : 0}, ${s.verdict === 'liked' ? 0 : 2}, ${q(new Date().toISOString())});`,
  );
}

// This week: requests waiting on Monday.
for (const s of CURRENT) {
  const id = ulid();
  event(THIS, 'added', id, PEOPLE[CURRENT.indexOf(s) % PEOPLE.length]!, s);
  for (let v = 1; v < s.votes; v++) event(THIS, 'voted', id, PEOPLE[(v + 1) % PEOPLE.length]!, undefined);
}

const file = join(tmpdir(), 'snack-bot-seed.sql');
writeFileSync(file, sql.join('\n') + '\n');

const remote = !process.argv.includes('--local');
console.log(`Seeding ${remote ? 'remote' : 'local'} D1 — last week ${LAST}, this week ${THIS}`);
try {
  execFileSync(
    'npx',
    ['wrangler', 'd1', 'execute', 'snack-bot', remote ? '--remote' : '--local', '--file', file, '--yes'],
    { stdio: 'inherit' },
  );
  console.log(
    `\nSeeded: ${DELIVERED.length} delivered last week with verdicts, ${CURRENT.length} requests this week.\n` +
      `Budget pinned at $${(BUDGET_CENTS / 100).toFixed(0)}; the cut line falls after the third item.\n` +
      `Next: /snack list, then /snack simulate action:digest.`,
  );
} finally {
  unlinkSync(file);
}
